move supported versions and cache path to docker file

diff --git a/containers/documentation.docker/buildLib b/containers/documentation.docker/buildLib
--- a/containers/documentation.docker/buildLib
+++ b/containers/documentation.docker/buildLib
@@ -242,61 +242,67 @@ out_markdown_leftovers() { #TODO REVIEW
     local book_pre="$3"
     local book_out="$4"
 
-    local ERRORS
+    local errors
 
     echo "+ 09 checking for remaining markdown snippets in the HTML in ${book_name} "
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '^##' {} \; -print) || ferr "markdown leftovers 1"
-    if [[ -n "${ERRORS}" ]]; then
+    errors=$(find "$book_out" -name '*.html' -exec grep -- '^##' {} \; -print) \
+        || ferr "markdown leftovers 1"
+    if [[ -n "${errors}" ]]; then
         err "found these unconverted markdown titles"
-        echo "${ERRORS}"
+        echo "${errors}"
         exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '&amp;gt;' {} \; -print) || ferr "markdown leftovers 2"
-    if [[ -n "${ERRORS}" ]]; then
+    errors=$(find "$book_out" -name '*.html' -exec grep -- '&amp;gt;' {} \; -print) \
+        || ferr "markdown leftovers 2"
+    if [[ -n "${errors}" ]]; then
         err "found these double converted > signs"
-        echo "${ERRORS}"
+        echo "${errors}"
         exit 1
     fi
 
-    local ERRORS=()
+    local errorsa=()
     while IFS= read -r line; do
-        grep -E '"[a-zA-Z/\.]*\.md\"[ />]' "$line" | grep -v data-filepath;
+        grep '"[a-zA-Z/\.]*\.md\"[ />]' "$line" | grep -v data-filepath
         local rv=$?
-        (( rv == 0 )) && ERRORS+=( "$line" )
+        (( rv == 0 )) && errorsa+=( "$line" )
         (( rv == 2 )) && ferr "markdown leftovers 3"
     done < <(find "$book_out" -name '*.html')
 
-    if [[ -n "${ERRORS[@]}" ]]; then
+    if [[ -n "${errorsa[@]}" ]]; then
         err "found dangling markdown links"
-        echo "${ERRORS[@]}"
+        echo "${errorsa[@]}"
         exit 1
 
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '"[a-zA-Z/\.]*\.md#' {} \; -print) || ferr "markdown leftovers 4"
-    if [[ -n "${ERRORS}" ]]; then
+    errors=$(find "$book_out" -name '*.html' -exec grep '"[a-zA-Z/\.]*\.md#' {} \; -print) \
+        || ferr "markdown leftovers 4"
+    if [[ -n "${errors}" ]]; then
         err "found dangling markdown links: "
-        echo "${ERRORS}"
+        echo "${errors}"
         exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep "${TRIPPLETICS}" {} \; -print) || ferr "markdown leftovers 5"
-    if [[ -n "${ERRORS}" ]]; then
+    errors=$(find "$book_out" -name '*.html' -exec grep "${TRIPPLETICS}" {} \; -print) \
+        || ferr "markdown leftovers 5"
+    if [[ -n "${errors}" ]]; then
         err "found dangling markdown code sections: "
-        echo "${ERRORS}"
+        echo "${errors}"
         exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\]<a href' {} \; -print) || ferr "markdown leftovers 6"
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\]<a href' {} \; -print) \
+        || ferr "markdown leftovers 6"
     if [[ -n "${ERRORS}" ]]; then
         err "found unconverted markdown links: "
         echo "${ERRORS}"
         exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\[.*\](.*[\.html|\.md|http|#.*])' {} \; -print) || ferr "markdown leftovers 7"
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\[.*\](.*[\.html|\.md|http|#.*])' {} \; -print) \
+        || ferr "markdown leftovers 7"
     if [[ -n "${ERRORS}" ]]; then
         err "found unconverted markdown links: "
         echo "${ERRORS}"
@@ -336,120 +342,6 @@ pp_check_html_link() {
 
 ################################################################################
 ### CROSS CHECKS ###############################################################
-
-
-
-cross_check_dangling_anchors() {
-    rm -rf /tmp/tags/
-
-    echo "+ 12 checking anchors"
-    echo "  - create tag structure" #OK
-    # go through html files
-    # find id="tags"
-    # write list of tags ot /tmp/tags/html_file_dir/html_flile_name_without_ext
-    local html_file_full
-    while IFS= read -r html_file_full; do
-        local file_name="${html_file_full##*/}"
-        local dir="${html_file_full%/*}"
-        mkdir -p "/tmp/tags/${dir}"
-        grep_ignore_empty '<h. ' "${html_file_full}" | \
-            sed -e 's;.*id=";;' -e 's;".*;;' > "/tmp/tags/${dir}/${file_name}" \
-            || ferr "failed creating tag structure"
-    done < <(find "$ARANGO_BUILD_DOC_OUT" -name '*.html')
-
-
-    echo "  - check if tags (files in /tmp/tags) are unique" #OK
-    local error_occured=false
-    while IFS= read -r htmlf; do
-        local errors=$( comm -3  <(sort    "${htmlf}" | grep -v ^$ ) \
-                                 <(sort -u "${htmlf}" | grep -v ^$ )
-                      ) || ferr "compare - unique tags failed"
-
-        if [[ -n "$errors" ]]; then
-            echo "in ${htmlf}: "
-            echo "$errors"
-            error_occured=true
-        fi
-    done < <(find /tmp/tags -type f)
-
-    if $error_occured; then
-        ferr "duplicate anchors detected - see above"
-    fi
-
-
-    echo "  - fetching anchors from generated http files" # TODO REVIEW
-    rm -f /tmp/anchorlist.txt
-    for file in $(find "$ARANGO_BUILD_DOC_OUT" -name \*.html); do
-        # - strip of the menu
-        # - then the page tail.
-        # - remove links to external pages
-        cat $file | \
-            sed -r -n -e '/normal markdown-section/,${p}'| \
-            sed -r -n -e '/.*id="page-footer".*/q;p' | \
-            grep_ignore_empty '<a href="' | \
-            grep_ignore_empty -v 'target="_blank"' | \
-            sed -e 's;.*href=";;' -e 's;".*;;' > /tmp/thisdoc.txt || { ls -lisah "$file"; ferr "fail cat $file"; }
-
-        if [[ -f /tmp/thisdoc.txt ]]; then
-            # Links with anchors:
-            cat /tmp/thisdoc.txt | grep_ignore_empty '#' | sed "s;\(.*\)#\(.*\);${file},\1,\2;" >> /tmp/anchorlist.txt || ferr "fail 1 cat thisdoc.txt for: $file"
-            # links without anchors:
-            cat /tmp/thisdoc.txt | grep_ignore_empty -v '#' | sed "s;\(.*\);${file},\1,;" >> /tmp/anchorlist.txt || ferr "fail 2 cat thisdoc.txt for file: $file"
-        fi
-    done
-    ## why do we create anchorlist above, when we delete it in the next lines?
-
-    echo "  - cross checking anchors" # OK
-    local debug_anchors=false
-    local dangling_anchor_count=0
-
-    # loop vars that
-    local anchor
-    local relative_filename
-    local full_filename
-
-    while IFS=',' read -r full_filename relative_filename anchor; do
-        $debug_anchors && debug "anchor $anchor"
-        $debug_anchors && debug "relative_filename $relative_filename"
-        $debug_anchors && debug "full_filename $full_filename"
-
-        local check_filename
-        if [[ -z "$relative_filename" ]]; then
-            $debug_anchors && debug "using fullname"
-            check_filename="$full_filename"
-        else
-            $debug_anchors && debug "using modified fullname"
-            check_filename="${full_filename%/*html}/${relative_filename}"
-        fi
-
-        $debug_anchors && debug $check_filename
-
-        if [[ -d "$check_filename" ]]; then
-            check_filename="${check_filename}/index.html"
-        fi
-
-        if  ! [[ -f "/tmp/tags/${check_filename}" ]]; then
-            err "File referenced by $anchor doesn't exist."
-            debug "file missing" && exit 1
-            (( dangling_anchor_count++ ))
-        else
-            if [[ -n "$anchor" ]]; then
-                if ! grep -q "^$anchor$" "/tmp/tags/${check_filename}"; then
-                    err "Anchor $anchor not found in $full_filename $relative_filename"
-                    dangling_anchor_count=$((dangling_anchor_count + 1))
-                    echo "available anchors in that file:"
-                    sort < "/tmp/tags/${check_filename}"
-                fi
-            fi
-        fi
-    done < /tmp/anchorlist.txt || ferr "failed in big loop"
-
-    if (( dangling_anchor_count > 0 )); then
-        ferr "${dangling_anchor_count} Dangling anchors found!"
-    fi
-
-    rm -rf /tmp/anchorlist.txt /tmp/tags
-}
 
 #************************************************************
 # Check docublocks - checks whether docublock are
@@ -519,14 +411,19 @@ function cross_check_docublocks() { #TODO review
 
     # These files are converted to docublocks on the fly and only live in memory.
     for file in "$ARANGO_SOURCE_DOC/Examples/"*.json ; do
-        echo "$file" |sed -e "s;.*/;Generated: @startDocuBlock program_options_;" -e "s;.json;;" >> /tmp/rawinprog.txt
+        echo "$file" | sed -e "s;.*/;Generated: @startDocuBlock program_options_;" \
+                           -e "s;.json;;" \
+        >> /tmp/rawinprog.txt
     done
 
     echo "Generated: startDocuBlockInline errorCodes">> /tmp/rawinprog.txt
     debug "lines  rawinprog $(cat /tmp/rawinprog.txt | wc -l)"
 
-    sed -e "s;\r$;;" -e "s;.*ck ;;" -e "s;.*ne ;;" < /tmp/rawinprog.txt  |sort > /tmp/inprog_raw.txt
+    sed -e "s;\r$;;" -e "s;.*ck ;;" -e "s;.*ne ;;" < /tmp/rawinprog.txt \
+        | sort > /tmp/inprog_raw.txt
+
     sort -u < /tmp/inprog_raw.txt > /tmp/inprog.txt
+
     debug "lines inprog $(cat /tmp/inprog.txt | wc -l)"
     #### in prog - end
     #########################################################
@@ -534,8 +431,7 @@ function cross_check_docublocks() { #TODO review
     #check for duplicates in DocuBlocks Dir
     echo "  - find duplicates in DoucBlock dir"
     if [[ "$(wc -l < /tmp/inprog.txt)" -ne "$(wc -l < /tmp/inprog_raw.txt)" ]]; then
-        echo ""
-        echo "Duplicate entry found in the source trees:"
+        err "Duplicate entry found in the source trees:"
         comm -3 /tmp/inprog_raw.txt /tmp/inprog.txt
         ferr "Duplicate entry found in the source trees:"
     fi
@@ -565,3 +461,115 @@ function cross_check_docublocks() { #TODO review
     fi
 }
 
+cross_check_dangling_anchors() {
+    rm -rf /tmp/tags/
+
+    echo "+ 12 checking anchors"
+    echo "  - create tag structure" #OK
+    # go through html files
+    # find id="tags"
+    # write list of tags ot /tmp/tags/html_file_dir/html_flile_name_without_ext
+    local html_file_full
+    while IFS= read -r html_file_full; do
+        local file_name="${html_file_full##*/}"
+        local dir="${html_file_full%/*}"
+        mkdir -p "/tmp/tags/${dir}"
+        grep_ignore_empty '<h. ' "${html_file_full}" | \
+            sed -e 's;.*id=";;' -e 's;".*;;' > "/tmp/tags/${dir}/${file_name}" \
+            || ferr "failed creating tag structure"
+    done < <(find "$ARANGO_BUILD_DOC_OUT" -name '*.html')
+
+
+    echo "  - check if tags (files in /tmp/tags) are unique" #OK
+    local error_occured=false
+    while IFS= read -r htmlf; do
+        local errors=$( comm -3  <(sort    "${htmlf}" | grep -v ^$ ) \
+                                 <(sort -u "${htmlf}" | grep -v ^$ )
+                      ) || ferr "compare - unique tags failed"
+
+        if [[ -n "$errors" ]]; then
+            echo "in ${htmlf}: "
+            echo "$errors"
+            error_occured=true
+        fi
+    done < <(find /tmp/tags -type f)
+
+    if $error_occured; then
+        ferr "duplicate anchors detected - see above"
+    fi
+
+
+    ### TODO REVIEW - End ############################################################
+    echo "  - fetching anchors from generated http files"
+    rm -f /tmp/anchorlist.txt
+    for file in $(find "$ARANGO_BUILD_DOC_OUT" -name \*.html); do
+        # - strip of the menu
+        # - then the page tail.
+        # - remove links to external pages
+        cat $file | \
+            sed -r -n -e '/normal markdown-section/,${p}'| \
+            sed -r -n -e '/.*id="page-footer".*/q;p' | \
+            grep_ignore_empty '<a href="' | \
+            grep_ignore_empty -v 'target="_blank"' | \
+            sed -e 's;.*href=";;' -e 's;".*;;' > /tmp/thisdoc.txt || { ls -lisah "$file"; ferr "fail cat $file"; }
+
+        if [[ -f /tmp/thisdoc.txt ]]; then
+            # Links with anchors:
+            cat /tmp/thisdoc.txt | grep_ignore_empty '#' | sed "s;\(.*\)#\(.*\);${file},\1,\2;" >> /tmp/anchorlist.txt || ferr "fail 1 cat thisdoc.txt for: $file"
+            # links without anchors:
+            cat /tmp/thisdoc.txt | grep_ignore_empty -v '#' | sed "s;\(.*\);${file},\1,;" >> /tmp/anchorlist.txt || ferr "fail 2 cat thisdoc.txt for file: $file"
+        fi
+    done
+    ### TODO - End ##################################################################
+
+    echo "  - cross checking anchors" # OK
+    local debug_anchors=false
+    local dangling_anchor_count=0
+
+    # loop vars that
+    local anchor
+    local relative_filename
+    local full_filename
+
+    while IFS=',' read -r full_filename relative_filename anchor; do
+        $debug_anchors && debug "anchor $anchor"
+        $debug_anchors && debug "relative_filename $relative_filename"
+        $debug_anchors && debug "full_filename $full_filename"
+
+        local check_filename
+        if [[ -z "$relative_filename" ]]; then
+            $debug_anchors && debug "using fullname"
+            check_filename="$full_filename"
+        else
+            $debug_anchors && debug "using modified fullname"
+            check_filename="${full_filename%/*html}/${relative_filename}"
+        fi
+
+        $debug_anchors && debug $check_filename
+
+        if [[ -d "$check_filename" ]]; then
+            check_filename="${check_filename}/index.html"
+        fi
+
+        if  ! [[ -f "/tmp/tags/${check_filename}" ]]; then
+            err "File referenced by $anchor doesn't exist."
+            debug "file missing" && exit 1
+            (( dangling_anchor_count++ ))
+        else
+            if [[ -n "$anchor" ]]; then
+                if ! grep -q "^$anchor$" "/tmp/tags/${check_filename}"; then
+                    err "Anchor $anchor not found in $full_filename $relative_filename"
+                    dangling_anchor_count=$((dangling_anchor_count + 1))
+                    echo "available anchors in that file:"
+                    sort < "/tmp/tags/${check_filename}"
+                fi
+            fi
+        fi
+    done < /tmp/anchorlist.txt || ferr "failed in big loop"
+
+    if (( dangling_anchor_count > 0 )); then
+        ferr "${dangling_anchor_count} Dangling anchors found!"
+    fi
+
+    rm -rf /tmp/anchorlist.txt /tmp/tags
+}
diff --git a/containers/documentation.docker/build_documentation b/containers/documentation.docker/build_documentation
--- a/containers/documentation.docker/build_documentation
+++ b/containers/documentation.docker/build_documentation
@@ -10,13 +10,8 @@
 
 # TODO
 #
-# - fix broken tests
 # - execute container with same permissions as calling user not root
-# - find out branch name
 # - add http.tar.gz package creation
-#
-#
-# - test other formats
 #
 
 
@@ -33,12 +28,17 @@ set -o pipefail
 #
 # variables that MUST be set before invoking the script
 #
-[[ $ARANGO_WORK ]] || ferr "path to work dir not set"
+[[ -v ARANGO_WORK ]] || ferr "path to work dir not set"
+[[ -d ARANGO_WORK ]] || ferr "work dir path is not a directory"
 # control if there is debug output or not
 ARANGO_DEBUG=true
 
 # variables that SHOULD be set before invoking the script
-#
+# this list must match the versions provided in setup_gitbook
+# usually both variables are set in the docker file
+[[ -v ARANGO_SUPPORTED_BRANCHES ]] || { echo "supported branches not set"; exit 1; }
+[[ -v ARANGO_CACHE_BASE ]] || { echo "arango cache base not set"; exit 1; }
+
 # path to "arangodb" source
 export ARANGO_SOURCE="${ARANGO_SOURCE:-"$ARANGO_WORK/ArangoDB"}"
 export ARANGO_SOURCE_DOC="${ARANGO_SOURCE_DOC:-"$ARANGO_SOURCE/Documentation"}"
@@ -83,6 +83,17 @@ ALLBOOKS="HTTP AQL Manual Cookbook Drivers"
 OTHER_MIME="pdf epub mobi"
 TRIPPLETICS='```'
 
+#get branch name
+cd "$ARANGO_SOURCE" || ferr "can not cd into source"
+branch_current="$(git rev-parse --abbrev-ref HEAD)" || ferr "can not get branch name"
+branch_to_use="not found"
+for name in $ARANGO_SUPPORTED_BRANCHES; do
+    if [[ $branch_current == $name ]]; then
+        branch_to_use="$name"
+    fi
+done
+[[ $branch_to_use == "not found" ]] && ferr "you currently checked out branch is not supported"
+
 newVersionNumber="$( tr -d '\r\n' < "$ARANGO_SOURCE/VERSION" )"
 #If ../../VERSION contains the string "devel" the current date will be added to all pages containing the version.
 
@@ -120,23 +131,30 @@ GITBOOK_ARGS=(--gitbook "${INSTALLED_GITBOOK_VERSION}")
 ### HELPER FUNCTIONS ###########################################################
 ################################################################################
 
-run_gitbook() {
+run_gitbook(){
+    local cache="$1"
+    local c=true
+    if [[ $cache == "" ]] || [[ $cache == "fake cache" ]]; then
+        c=false
+    fi
+    shift
     local cmd=( gitbook "${GITBOOK_ARGS[@]}" "$@" )
+
     echo "run ${cmd[@]}"
     if ! time "${cmd[@]}" ; then
         echo "==============================================================================="
-        echo "## install log  ###############################################################"
-        cat "$cache/book_install.log"
-        echo "## book.json at install########################################################"
-        cat "$cache/book.json_at_install"
-        echo "## diff #######################################################################"
-        diff book.json "$cache/book.json_at_install"
+        $c && echo "## install log  ###############################################################"
+        $c && cat "$cache/book_install.log"
+        $c && echo "## book.json at install########################################################"
+        $c && cat "$cache/book.json_at_install"
+        $c && echo "## diff #######################################################################"
+        $c && diff book.json "$cache/book.json_at_install"
         echo "## book.json ##################################################################"
         cat book.json
         echo "## modules ####################################################################"
         ls -lisah node_modules
-        echo "###############################################################################"
-        echo "try to run ./scripts/buildContainerDocumentation --force-update if modules are missing"
+        $c && echo "###############################################################################"
+        $c && echo "try to run ./scripts/buildContainerDocumentation --force-update if modules are missing"
         ferr "running gitbook failed"
         echo "==============================================================================="
     fi
@@ -277,17 +295,14 @@ function build_book() {
         fi
     done
 
-
     section " Building Book - ${book_name} "
-
     #copy gitbook modules from cache in build image
     say " - copy node modules"
-    local i="devel" #TODO FIXME get - calculate version to use
-    local cache="/root/gitbook_cache/$i/$book_name"
+    local cache="$ARANGO_CACHE_BASE/$branch_to_use/$book_name"
     cp -r "$cache/node_modules" "$book_pre" || ferr "failed to copy node modules"
 
     say " - run gitbook"
-    run_gitbook build "$book_pre" "$book_out" || ferr "fail"
+    run_gitbook "$cache" build "$book_pre" "$book_out" || ferr "fail exectuting run_gitbook"
 
 
     section " Clean Up - Book ${book_name} "
@@ -431,7 +446,7 @@ main(){
         for book_name in $ALLBOOKS; do
             for format in $OTHER_MIME; do
                 local out="${ARANGO_BUILD_DOC}/ArangoDB_${book_name}_${newVersionNumber}.${format}"
-                run_gitbook "${GITBOOK_ARGS[@]}" "${format}" "$ARANGO_BUILD_DOC_PRE/$book_name" "${out}" || ferr "fail"
+                run_gitbook "fake cache" "${GITBOOK_ARGS[@]}" "${format}" "$ARANGO_BUILD_DOC_PRE/$book_name" "${out}" || ferr "fail"
             done
         done
     fi
diff --git a/containers/documentation.docker/setup_gitbook b/containers/documentation.docker/setup_gitbook
--- a/containers/documentation.docker/setup_gitbook
+++ b/containers/documentation.docker/setup_gitbook
@@ -1,15 +1,18 @@
 #!/bin/bash
 export NVM_DIR=/usr/local/nvm
 . $NVM_DIR/nvm.sh
-nvm use stable || { echo "could not use nvm"; exit 1; }
-npm install gitbook-cli -g || { echo "could not install gitbook-cli"; exit 1; }
+ferr(){ echo "$@"; exit 1; }
 
-cache_base="/root/gitbook_cache"
-mkdir -p "$cache_base"
-cd "$cache_base"
-creation_date <<<"$(date)"
+[[ -v ARANGO_SUPPORTED_BRANCHES ]] || ferr "supported branches not set"
+[[ -v ARANGO_CACHE_BASE ]] || ferr "arango cache base not set";
 
-for i in 3.0 3.1 3.2 3.3 3.4 devel; do
+nvm use stable || ferr "could not use nvm"
+npm install gitbook-cli -g || ferr "could not install gitbook-cli"
+
+cache_base="$ARANGO_CACHE_BASE"
+mkdir -p "$cache_base" && cd "$cache_base" || ferr "failed to create cache dir"
+
+for i in $ARANGO_SUPPORTED_BRANCHES; do
     cache="$cache_base/$i"
     mkdir -p "$cache"
     cd "$cache"
@@ -19,14 +22,18 @@ for i in 3.0 3.1 3.2 3.3 3.4 devel; do
         echo "Installing modules for book: $book in version $i"
         mkdir "$book" && cd "$book"
         rm -fr book.json
-        if ! curl --fail -O https://raw.githubusercontent.com/arangodb/arangodb/$i/Documentation/Books/${book}/book.json; then
-            echo "could not download: https://raw.githubusercontent.com/arangodb/arangodb/$i/Documentation/Books/${book}/book.json continue"
+        url="https://raw.githubusercontent.com/arangodb/arangodb/"
+        url+="$i/Documentation/Books/${book}/book.json"
+        if ! curl --fail -O "$url"; then
+            echo "could not download $url continue"
             continue
         fi
 
+        ## replace templates with some random strings so we
+        ## are able to install
         sed -e "s;@GCHANGE_FREQ@;daily};" \
             -e "s;@GPRIORITY@;0.3;" \
-            -i "book.json"
+            -i "book.json" || ferr "failed to replace templates"
 
         echo "calling 'gitbook install' on 'book.json' : << HERE"
         cat book.json
@@ -35,6 +42,6 @@ for i in 3.0 3.1 3.2 3.3 3.4 devel; do
         gitbook install -g &> book_install.log || { echo "Failed to install modules"; cat book.json; exit 1; }
         mv book.json book.json_at_install
     done
-done
+done 2>&1 | tee set_gitbook.log
 
 echo "git book modules successfully installed"
