readd missing test

diff --git a/containers/documentation.docker/buildLib b/containers/documentation.docker/buildLib
--- a/containers/documentation.docker/buildLib
+++ b/containers/documentation.docker/buildLib
@@ -236,37 +236,6 @@ src_check_images_referenced() { #DONE
 ################################################################################
 ### POST CHECKS ################################################################
 
-pp_check_html_link() {
-    local book_name="$1"
-    local book_src="$2"
-    local book_pre="$3"
-    local book_out="$4"
-
-    # TODO description
-
-    set -o pipefail
-    book_name="$1"
-    msg="$2"
-    echo "##### checking for invalid HTML links in ${book_name}"
-    echo "${ALLBOOKS}" | tr " " "\n" | sed -e 's;^;/;' -e 's;$;/;' > /tmp/books.regex
-
-    grep -r -E '\[.*\]\(.*\)' "$book_pre"| \
-        grep '\.md:'| grep 'html'| \
-        grep -v 'http://' | \
-        grep -v 'https://' | \
-        grep -v 'header.css' | \
-        grep -v -f /tmp/books.regex > /tmp/relative_html_links.txt
-
-        #no lines matched
-        (( $? == 1 )) && return 0
-
-    if [[ "$(wc -l < /tmp/relative_html_links.txt)" -gt 0 ]]; then
-        echo "Found links to .html files inside of the document! use <foo>.md instead!"
-        cat  /tmp/relative_html_links.txt
-        exit 1
-    fi
-}
-
 out_markdown_leftovers() {
     # TODO description
     local book_name="$1"
@@ -332,6 +301,36 @@ out_markdown_leftovers() {
     if [[ -n "${ERRORS}" ]]; then
         err "found unconverted markdown links: "
         echo "${ERRORS}"
+        exit 1
+    fi
+}
+
+pp_check_html_link() {
+    local book_name="$1"
+    local book_src="$2"
+    local book_pre="$3"
+    local book_out="$4"
+
+    # TODO description
+
+    set -o pipefail
+    book_name="$1"
+    msg="$2"
+    echo "##### 10 checking for invalid HTML links in ${book_name}"
+
+    for book in $ALLBOOKS; do echo "/$book/"; done > /tmp/books.regex
+
+    grep -r -E '\[.*\]\(.*\)' "$book_pre"| \
+        grep '\.md:'| grep 'html'| \
+        grep -v 'http://' | \
+        grep -v 'https://' | \
+        grep -v 'header.css' | \
+        grep -v -f /tmp/books.regex > /tmp/relative_html_links.txt
+
+
+    if [[ $(wc -l < /tmp/relative_html_links.txt) != "0" ]]; then
+        echo "Found links to .html files inside of the document! use <foo>.md instead!"
+        cat  /tmp/relative_html_links.txt
         exit 1
     fi
 }
