continue work

diff --git a/containers/documentation.docker/buildLib b/containers/documentation.docker/buildLib
--- a/containers/documentation.docker/buildLib
+++ b/containers/documentation.docker/buildLib
@@ -70,7 +70,7 @@ pp_check_leftover_docublocks() {
     #in ppdir
     echo "##### 4 checking for left over docublocks in ${name}"
     ERRORS="$(grep -rl "startDocuBlock" --include "*.md" "$book_ppdir")"
-    (( $? > 1)) && ferr "Failed running chek for leftover DocuBlocks"
+    (( $? > 1 )) && ferr "Failed running chek for leftover DocuBlocks"
     if [[ -n "${ERRORS}" ]]; then
         echo "startDocuBlock markers still found in generated output files:"
         echo "${ERRORS}" | sed -e "s/^/- /g"
@@ -97,53 +97,55 @@ pp_check_restheader_leftovers() {
     echo "##### 5 checking for restheader leftovers in ${name}"
     ERRORS="$(find "$book_ppdir"  -path "*/Drivers/SpringData/*" -prune  -o -name "*.md" -exec bash -c 'grep -E -q -- "^@[A-Z]*" "$1" && echo $1' -- '{}' \; )" || failed "check for restheader leftovers"
     if [[ -n "${ERRORS}" ]]; then
-        echo ""
         echo "found these unconverted Swagger Restapi tags: "
         echo "${ERRORS}"
-        echo ""
         exit 1
     fi
 }
 
-function ppbook-check-two-links()
-{
+pp_check_two_links() {
     # TODO description
     local name="$1"
     local book_source="$2"
     local book_ppdir="$3"
     local book_out="$4"
-    NAME="$1"
-    echo "##### 6 checking for two links in a single line in ${NAME}"
-    ERRORS=$(find "ppbooks/${NAME}" \
-                  -path "ppbooks/${NAME}/node_modules" \
+
+    #in ppdir
+    local ERRORS=()
+    echo "##### 6 checking for two links in a single line in ${name}"
+    while IFS= read -r ppfile; do
+        local search=$(grep -e '](.*](' "${ppfile}")
+        (( $? > 1 )) && ferr "fail in check two links"
+        local ERR="$(echo "$search" | grep -v '|' )"
+        if [[ -n "${ERR}" ]]; then
+            ERRORS+=( "\n${ppfile}: \n ${ERR}" )
+        fi
+    done < <(find "$book_ppdir" \
+                  -path "$book_ppdir/node_modules*" \
                   -prune -o \
                   -name '*.md' \
-                  -print | while IFS= read -r ppfile; do
-                 ERR=$(grep -e '](.*](' "${ppfile}" | grep -v '|'||true)
-                 if test -n "${ERR}"; then
-                     printf "\n${ppfile}: \n ${ERR}"
-                 fi
-             done
-          )
-    if test "$(printf "${ERRORS}" | wc -l)" -gt 0; then
-        echo "";
+                  -print
+            ) || ferr "failed checking for two links"
+
+    if [[ "${ERRORS[@]}" ]]; then
         echo "found these files with two links in one line: "
-        echo "${ERRORS}"
-        echo "";
+        echo "${ERRORS[@]}"
         exit 1;
     fi
 }
 
-function ppbook-check-directory-link()
+function pp_check_directory_link()
 {
     # TODO description
     local name="$1"
     local book_source="$2"
     local book_ppdir="$3"
     local book_out="$4"
-    NAME="$1"
-    echo "##### 7 checking for invalid md links in ${NAME}"
-    ERRORS=$(grep -r -E '\[.*\]\(.*\)' "ppbooks/${NAME}" | \
+
+
+    #in ppdir
+    echo "##### 7 checking for invalid md links in ${name}"
+    local ERRORS=$( grep -r -E '\[.*\]\(.*\)' "$book_ppdir" | \
                     grep '\.md:' | \
                     grep -v html | \
                     grep -v http://| \
@@ -151,66 +153,65 @@ function ppbook-check-directory-link()
                     grep -v header.css | \
                     grep -v node_modules | \
                     grep -v node_modules | \
-                    grep -v '\.md')
-    nERRORS=$(echo -n "${ERRORS}" | wc -l)
-    if test "$nERRORS" -gt 0; then
-        echo ""
-        echo "Found director links! use ../<directory>/README.md instead!"
+                    grep -v '\.md') || ferr "failed checking for invalid links"
+
+
+    if [[ -n "$ERRORS" ]]; then
+        echo "Found directory links! use ../<directory>/README.md instead!"
         echo "${ERRORS}"
-        echo ""
         exit 1
     fi
 }
 
-function book-check-images-referenced()
+function src_check_images_referenced()
 {
     # TODO description
     local name="$1"
     local book_source="$2"
     local book_ppdir="$3"
     local book_out="$4"
-    NAME="$1"
-    echo "##### 8 checking for unused image files ${NAME}"
-    ERRORS=$(find "${NAME}" -name '*.png' | while IFS= read -r image; do
-            baseimage=$(basename "$image")
-            if ! grep -Rq "${baseimage}" "${NAME}"; then
-                printf "\n${image}"
-            fi
-        done
-    )
-    if test "$(printf "${ERRORS}" | wc -l)" -gt 0; then
-        echo "";
-        echo "the following images are not referenced by any page: "
-        echo "${ERRORS}"
-        echo "";
-        exit 1;
-    fi
+
+    echo "##### 8 checking for unused image files ${name}"
+    local found=false
+    while IFS= read -r image; do
+        baseimage=$(basename "$image")
+        if ! grep -Rq "${baseimage}" "${name}"; then
+            ! $found && { echo "the following images are not referenced by any page: " ; found=true; }
+            printf "\n${image}"
+        fi
+    done < <(find "${name}" -name '*.png')
+    $found && exit 1;
 }
 
 # checks we do not reach yet
 
-function ppbook-check-html-link()
-{
+pp_check_html_link() {
+    local name="$1"
+    local book_source="$2"
+    local book_ppdir="$3"
+    local book_out="$4"
+
     # TODO description
+
     set -o pipefail
-    NAME="$1"
-    MSG="$2"
-    echo "##### zzz checking for invalid HTML links in ${NAME}"
+    name="$1"
+    msg="$2"
+    echo "##### checking for invalid HTML links in ${name}"
     echo "${ALLBOOKS}" | tr " " "\n" | sed -e 's;^;/;' -e 's;$;/;' > /tmp/books.regex
 
-    grep -r -E '\[.*\]\(.*\)' "ppbooks/${NAME}"| \
+    grep -r -E '\[.*\]\(.*\)' "$book_ppdir"| \
         grep '\.md:'| grep 'html'| \
         grep -v 'http://' | \
         grep -v 'https://' | \
         grep -v 'header.css' | \
         grep -v -f /tmp/books.regex > /tmp/relative_html_links.txt
 
-    if test "$(wc -l < /tmp/relative_html_links.txt)" -gt 0; then
-        echo ""
+        #no lines matched
+        (( $? == 1 )) && return 0
+
+    if [[ "$(wc -l < /tmp/relative_html_links.txt)" -gt 0 ]]; then
         echo "Found links to .html files inside of the document! use <foo>.md instead!"
-        echo "${MSG}"
         cat  /tmp/relative_html_links.txt
-        echo ""
         exit 1
     fi
 }
@@ -218,60 +219,81 @@ function ppbook-check-html-link()
 book_check_post_build_markdown_leftovers() {
     # TODO description
     local name="$1"
-    local book_out="$2"
+    local book_source="$2"
+    local book_ppdir="$3"
+    local book_out="$4"
+
+    local ERRORS
+
     echo "##### checking for remaining markdown snippets in the HTML output of ${name} in $book_out"
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '^##' {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '^##' {} \; -print) || ferr "markdown leftovers 1"
     if [[ -n "${ERRORS}" ]]; then
+        err "found these unconverted markdown titles"
         echo "${ERRORS}"
-        ferr "found these unconverted markdown titles"
+        exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '&amp;gt;' {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep -- '&amp;gt;' {} \; -print) || ferr "markdown leftovers 2"
     if [[ -n "${ERRORS}" ]]; then
+        err "found these double converted > signs"
         echo "${ERRORS}"
-        ferr "found these double converted > signs"
+        exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '"[a-zA-Z/\.]*\.md\"[ />]' {} \; -print | grep -v data-filepath)
-    if [[ -n "${ERRORS}" ]]; then
-        echo "${ERRORS}"
-        ferr "found dangling markdown links; see the list above "
+    local ERRORS=()
+    while IFS= read -r line; do
+        grep -E '"[a-zA-Z/\.]*\.md\"[ />]' "$line" | grep -v data-filepath;
+        local rv=$?
+        (( rv == 0 )) && ERRORS+=( "$line" )
+        (( rv == 2 )) && ferr "markdown leftovers 3"
+    done < <(find "$book_out" -name '*.html')
+
+    if [[ -n "${ERRORS[@]}" ]]; then
+        err "found dangling markdown links"
+        echo "${ERRORS[@]}"
+        exit 1
+
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '"[a-zA-Z/\.]*\.md#' {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep '"[a-zA-Z/\.]*\.md#' {} \; -print) || ferr "markdown leftovers 4"
     if [[ -n "${ERRORS}" ]]; then
+        err "found dangling markdown links: "
         echo "${ERRORS}"
-        ferr "found dangling markdown links: "
+        exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep "${TRIPPLETICS}" {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep "${TRIPPLETICS}" {} \; -print) || ferr "markdown leftovers 5"
     if [[ -n "${ERRORS}" ]]; then
+        err "found dangling markdown code sections: "
         echo "${ERRORS}"
-        ferr "found dangling markdown code sections: "
+        exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\]<a href' {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\]<a href' {} \; -print) || ferr "markdown leftovers 6"
     if [[ -n "${ERRORS}" ]]; then
+        err "found unconverted markdown links: "
         echo "${ERRORS}"
-        ferr "found unconverted markdown links: "
+        exit 1
     fi
 
-    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\[.*\](.*[\.html|\.md|http|#.*])' {} \; -print)
+    ERRORS=$(find "$book_out" -name '*.html' -exec grep '\[.*\](.*[\.html|\.md|http|#.*])' {} \; -print) || ferr "markdown leftovers 7"
     if [[ -n "${ERRORS}" ]]; then
+        err "found unconverted markdown links: "
         echo "${ERRORS}"
-        ferr "found unconverted markdown links: "
+        exit 1
     fi
 }
 
 
-function check-dangling-anchors()
+function cross_check_dangling_anchors()
 {
     # TODO description
     rm -rf /tmp/tags/
     echo "##### checking for dangling anchors"
-    find books/ -name '*.html' | while IFS= read -r htmlf; do
+    find "$ARANGO_BUILD_DOC_BOOKS" -name '*.html' | while IFS= read -r htmlf; do
         fn=$(basename "${htmlf}")
+        echo $fn
         dir=$(sed "s;/$fn;;" <<< "$htmlf")
         mkdir -p "/tmp/tags/${dir}"
         grep '<h. ' < "${htmlf}" | \
@@ -314,7 +336,6 @@ function check-dangling-anchors()
         cat /tmp/thisdoc.txt |grep '#' | sed "s;\(.*\)#\(.*\);${file},\1,\2;" >> /tmp/anchorlist.txt
         # links without anchors:
         cat /tmp/thisdoc.txt |grep -v '#' | sed "s;\(.*\);${file},\1,;" >> /tmp/anchorlist.txt
-
     done
 
     echo "##### cross checking anchors"
@@ -375,26 +396,11 @@ function check-dangling-anchors()
 #  - unique in the source
 #  - all docublocks are used somewhere in the documentation
 #
-function check-docublocks()
+function cross_check_docublocks()
 {
-    # TODO description
-    # set -o pipefail
-    # #set -e
-    # pwd
-    # ls -lisahd ./ppbooks/Summary.md
-    # ls -lisah ./ppbooks/*md
-    # debug "not found 1"
 
-    # grep -R '@startDocuBlock' \
-    #      --include "*.h" \
-    #      --include "*.cpp" \
-    #      --include "*.js" \
-    #      --include "*.md" \
-    #      . \
-    #      1>/dev/null || ferr "grep failed"
-
-
-
+    #cd "$ARANGO_BUILD_DOC_BOOKS"
+    pwd
 
     grep -R '@startDocuBlock' --include "*.h" --include "*.cpp" --include "*.js" --include "*.md" . |\
         grep -v '@startDocuBlockInline' |\
@@ -404,10 +410,13 @@ function check-docublocks()
         grep -v Makefile |\
         grep -v '.*~:.*' |\
         grep -v '.*#.*:.*' \
-             > /tmp/rawindoc.txt
-    debug "not found 1 - end"
+             > /tmp/rawindoc.txt || err "failed search for startDocuBlock - with $?"
+    ###
+    echo "in rawdoc"
+    cat /tmp/rawindoc.txt | wc -l
 
-    debug "not found 2"
+
+
     grep -R '@startDocuBlockInline' --include "*.h" --include "*.cpp" --include "*.js" --include "*.md" . |\
         grep -v ppbook |\
         grep -v stash |\
@@ -415,12 +424,15 @@ function check-docublocks()
         grep -v Makefile |\
         grep -v '.*~:.*' |\
         grep -v '.*#.*:.*' \
-             >> /tmp/rawindoc.txt
-    debug "not found 2 - end"
-    sed  -e "s;\r$;;" -e "s;.*ck ;;" -e "s;.*ne ;;" < /tmp/rawindoc.txt |sort -u > /tmp/indoc.txt
+             >> /tmp/rawindoc.txt || err "failed to search for startDocuBlockInline - with $?"
+    sed  -e "s;\r$;;" -e "s;.*ck ;;" -e "s;.*ne ;;" < /tmp/rawindoc.txt | sort -u > /tmp/indoc.txt
+    ###
+    echo "in doc"
+    cat /tmp/rawindoc.txt | wc -l
 
-    debug "not found 3"
-    grep -R '^@startDocuBlock' ../DocuBlocks --include "*.md" |grep -v aardvark > /tmp/rawinprog.txt
+
+
+    grep -R '^@startDocuBlock' "$ARANGO_SOURCE_DOC/DocuBlocks" --include "*.md" |grep -v aardvark > /tmp/rawinprog.txt
     # searching the Inline docublocks needs some more blacklisting:
     grep -R '@startDocuBlockInline' --include "*.h" --include "*.cpp" --include "*.js" --include "*.md" . |\
         grep -v ppbook |\
@@ -429,11 +441,13 @@ function check-docublocks()
         grep -v build.sh |\
         grep -v '.*~:.*' |\
         grep -v '.*#.*:.*' \
-             >> /tmp/rawinprog.txt
-    debug "not found 3 - end"
+             >> /tmp/rawinprog.txt || err "failed to search for startDocuBlock in source - with $?"
+    ###
+    echo "in prog"
+    cat /tmp/rawinprog.txt | wc -l
 
     # These files are converted to docublocks on the fly and only live in memory.
-    for file in ../Examples/*.json ; do
+    for file in "$ARANGO_SOURCE_DOC/Examples/"*.json ; do
         echo "$file" |sed -e "s;.*/;Generated: @startDocuBlock program_options_;" -e "s;.json;;" >> /tmp/rawinprog.txt
     done
     echo "Generated: startDocuBlockInline errorCodes">> /tmp/rawinprog.txt
@@ -444,10 +458,7 @@ function check-docublocks()
         echo ""
         echo "Duplicate entry found in the source trees:"
         comm -3 /tmp/inprog_raw.txt /tmp/inprog.txt
-        echo ""
-        echo "${1}"
-        echo ""
-        exit 1
+        ferr "Duplicate entry found in the source trees:"
     fi
 
     if test "$(comm -3 /tmp/indoc.txt /tmp/inprog.txt |wc -l)" -ne 0; then
@@ -467,10 +478,7 @@ function check-docublocks()
                 grep "$grepit" /tmp/rawinprog.txt | sed "s;/// @startDocuBlock;\t\t;"
             done
         fi
-        echo ""
-        echo "${1}"
-        echo ""
-        exit 1
+        ferr "Not all blocks were found on both sides:"
     fi
 }
 
