add better plugin detection

diff --git a/containers/documentation.docker/entrypoint b/containers/documentation.docker/entrypoint
--- a/containers/documentation.docker/entrypoint
+++ b/containers/documentation.docker/entrypoint
@@ -41,29 +41,32 @@ export ARANGO_BUILD_DOC="$ARANGO_WORK/build-documentation"
 export ARANGO_BUILD_DOC_PRE="$ARANGO_BUILD_DOC/books_pp"
 export ARANGO_BUILD_DOC_OUT="$ARANGO_BUILD_DOC/books_html"
 
-cd /oskar || { ls -lisah /oskar;  ferr "can not chage into /oskar"; }
-
 cd "$ARANGO_SOURCE" || { echo "could not change in arangodb source directroy"; exit 1; }
-ls -lisah ./build &>/dev/null || echo "no build directory"
-ls -lisah ./build/bin &>/dev/null || echo "unable to access source/bild/bin"
 
-[[ -e ./build/bin/arangod ]] || { echo "no arangod installed"; exit 1; }
+#TODO check .git/config instead
+[[ -f VERSION ]]  ||  { echo "please make sure you are in a valid checkout"; exit 1; }
+[[ -f VERSIONS ]] ||  { echo "please make sure you are in a valid checkout"; exit 1; }
+
+#ls -lisah ./build &>/dev/null || echo "no build directory"
+#ls -lisah ./build/bin &>/dev/null || echo "unable to access source/bild/bin"
 
 if $skip_examples; then
     echo "skip generate examples"
 else
-    if ./build/bin/arangod -version | grep -q "enterprise"; then
-        echo "########################################################"
-        echo "./build/bin/arangod --version"
-        ./build/bin/arangod --version
-        echo "########################################################"
-        echo "arangod needs to be compiled as community edition!"
-        echo "You can skip example generation with --skip-examples!!!"
-        exit 1
-     else
+    [[ -e ./build/bin/arangod ]] || { echo "no arangod exexutable available"; exit 1; }
+
+    # if ./build/bin/arangod -version | grep -q "enterprise"; then
+    #     echo "########################################################"
+    #     echo "./build/bin/arangod --version"
+    #     ./build/bin/arangod --version
+    #     echo "########################################################"
+    #     echo "arangod needs to be compiled as community edition!"
+    #     echo "You can skip example generation with --skip-examples!!!"
+    #     exit 1
+    # else
         echo "run generate examples"
         ./utils/generateExamples.sh || { echo "failed to generate examples!"; exit 1; }
-    fi
+    #fi
 fi
 
 if $skip_swagger; then
