ensure community edition is used for example generation

diff --git a/containers/documentation.docker/entrypoint b/containers/documentation.docker/entrypoint
--- a/containers/documentation.docker/entrypoint
+++ b/containers/documentation.docker/entrypoint
@@ -7,6 +7,8 @@ export NVM_DIR="${NVM_DIR:-/usr/local/nvm}"
 nvm use default || ferr "could not activate nvm"
 
 set -u
+set -o pipefail
+
 skip_examples=false
 skip_swagger=false
 for arg in "$@"; do
@@ -46,32 +48,39 @@ ls -lisah ./build/bin &>/dev/null || echo "unable to access source/bild/bin"
 [[ -e ./build/bin/arangod ]] || { echo "no arangod installed"; exit 1; }
 
 if $skip_examples; then
-  echo "skip generate examples"
+    echo "skip generate examples"
 else
-  echo "run generate examples"
-  ./utils/generateExamples.sh || { echo "failed to generate examples!"; exit 1; }
+    if [[ ./build/bin/arangod -version | grep -q "enterprise-version: cummunity" ]]; then
+        echo "run generate examples"
+        ./utils/generateExamples.sh || { echo "failed to generate examples!"; exit 1; }
+     else
+         echo "arangod needs to be compiles in community edition"
+         ./build/bin/arangod --version
+         echo "arangod needs to be compiles in community edition"
+         echo "you can skip example generation with --skip-examples"
+    fi
 fi
 
 if $skip_swagger; then
   echo "skip generate swagger"
 else
-  echo "generate swagger"
+    echo "generate swagger"
 
-  #TODO ./utils/generateSwagger.sh - must be deleted
-  cmd=( 'python'
-        "$PWD/utils/generateSwagger.py"
-        "$PWD"
-        "$PWD/js/apps/system/_admin/aardvark/APP/api-docs"
-        'api-docs'
-        "$PWD/Documentation/DocuBlocks/Rest"
-      )
-  echo "run ${cmd[@]}"
-  "${cmd[@]}" > $PWD/js/apps/system/_admin/aardvark/APP/api-docs.json \
-    || { echo "failed to generate swagger"; exit 1; }
+    #TODO ./utils/generateSwagger.sh - must be deleted
+    cmd=( 'python'
+          "$PWD/utils/generateSwagger.py"
+          "$PWD"
+          "$PWD/js/apps/system/_admin/aardvark/APP/api-docs"
+          'api-docs'
+          "$PWD/Documentation/DocuBlocks/Rest"
+        )
+    echo "run ${cmd[@]}"
+    "${cmd[@]}" > $PWD/js/apps/system/_admin/aardvark/APP/api-docs.json \
+      || { echo "failed to generate swagger"; exit 1; }
 
-  ls -lisah js/apps/system/_admin/aardvark/APP/api-docs.json
+    ls -lisah js/apps/system/_admin/aardvark/APP/api-docs.json
 
-  #./utils/generateSwagger.sh || { echo "failed to generate swagger"; exit 1; }
+    #./utils/generateSwagger.sh || { echo "failed to generate swagger"; exit 1; }
 fi
 
 echo "calling build_documenation"
